Add basic prototype
trailofbits/MUI pull request #15
Opened 2021-07-12 18:01 UTC by tcode2k16

2021-07-12 18:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/trailofbits/MUI?pullRequest=15) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/trailofbits/MUI?pullRequest=15) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/trailofbits/MUI?pullRequest=15) it.</sub>

2021-07-12 18:22 UTC, ekilmer requested changes
Could you also update the README, please

2021-07-12 20:43 UTC, ekilmer requested changes
Looking good! Would be nice to have some docstrings and more typing for function arguments.

2021-07-12 20:43 UTC, ekilmer commented on mui/mui.py
> +            "Angr Solve",
```suggestion
            "Manticore Solve",
```

2021-07-12 22:51 UTC, tcode2k16 commented
I made some more changes based on feedback and tested the code on both mac and linux. This pull request should now meet all acceptance criteria for #1

2021-07-13 13:44 UTC, ekilmer commented on mui/mui.py
> +        # Write the binary to disk so that the angr API can read it
```suggestion
        # Write the binary to disk so that the Manticore API can read it
```

2021-07-13 13:44 UTC, ekilmer commented on mui/mui.py
> +        BackgroundTaskThread.__init__(self, "Solving with manticore...", True)
```suggestion
        BackgroundTaskThread.__init__(self, "Solving with Manticore...", True)
```

2021-07-13 13:48 UTC, ekilmer commented on mui/mui.py
> +        self.avoid = tuple(avoid)
Good catch for making these collections immutable when handling them with Manticore 👍  💯

2021-07-13 16:35 UTC, tcode2k16 commented on requirements.txt
> +-e './manticore[native]'
Yes, I'm able to get autocompletion and type hints working in PyCharm by including paths to Binary Ninja's Python folders. I'm not sure how much typing information `mypy` is able to use, but thus far I have not run into any issues with that.

2021-07-13 16:37 UTC, ekilmer approved these changes
Great! LGTM

2021-07-13 16:38 UTC, sschriner commented on requirements.txt
> +-e './manticore[native]'
My issue was derived in the fact I had not switched to the development version, so this suggestion is irrelevant

2021-07-13 17:27 UTC, merged